var teamScores=[];var canvas=document.getElementById("canvas");var ctx=canvas.getContext("2d");var messages=[];var leaderboard=[];var ws=null;var nodeX=0;var nodeY=0;var nodesOnScreen=[];var playerCells=[];var nodes={};var nodelist=[];var Cells=[];var rawMouseX=0;var rawMouseY=0;var X=-1;var Y=-1;var timestamp=0;var userNickName=null;var leftPos=0;var topPos=0;var rightPos=1E4;var bottomPos=1E4;var viewZoom=.1;var showName=true;var userScore=0;var posX=nodeX=~~((leftPos+rightPos)/2);
var posY=nodeY=~~((topPos+bottomPos)/2);var posSize=1;var zoom=.3;var minX=0;var minY=0;var maxX=0;var isWatching=false;var isTyping=false;var maxY=0;var noRanking=false;var options={delay:140,squareMode:false,sectors:true,borders:true,cellalpha:false,bgColour:"222222",borderColour:"35B597",sectorColour:"313031",hideFood:false,ERTP:false,noMass:false,chathi:false,noNames:false};connect("ws://gk.agar.kr:2900")
var fps={startTime:0,frameNumber:0,getFPS:function(){this.frameNumber++;var d=(new Date).getTime(),currentTime=(d-this.startTime)/1E3,result=Math.floor(this.frameNumber/currentTime);if(currentTime>1){this.startTime=(new Date).getTime();this.frameNumber=0}return result}};
function Main(){document.getElementById("canvas").focus();canvas=document.getElementById("canvas");canvas.onmousemove=function(event){rawMouseX=event.clientX;rawMouseY=event.clientY;updateMouse()};document.body.onmousewheel=handleWheel;window.onresize=canvasResize;$(document).on("ready",function(){$("#nick").change(function(){localStorage.setItem("nick",document.getElementById("nick").value)});$("#skinUrl").change(function(){localStorage.setItem("skinurl",document.getElementById("skinUrl").value)});
$("#nick").val(localStorage.getItem("nick"));$("#skinUrl").val(localStorage.getItem("skinurl"))});if(window.requestAnimationFrame)reDraw();setInterval(sendMouseMove,1);canvasResize();$("#overlays").fadeIn(600)}function updateMouse(){X=(rawMouseX-ctx.canvas.width/2)/viewZoom+nodeX;Y=(rawMouseY-ctx.canvas.height/2)/viewZoom+nodeY}
function updateWindowFunctions(){window.onkeydown=function(event){if(isTyping===true&&event.keyCode!==13)return;switch(event.keyCode){case 81:sendUint8(18);break;case 32:sendUint8(17);break;case 87:sendUint8(21);break;case 80:if(options.ERTP===false)return;sendUint8(25);break;case 84:if(options.ERTP===false)return;sendUint8(24);break;case 82:if(options.ERTP===false)return;sendUint8(23);break;case 69:if(options.ERTP===false)return;sendUint8(22);break;case 27:showOverlays(true);break;case 13:var textBox=
document.getElementById("chat");if(textBox.value.length===0)textBox.focus();else{switch(textBox.value){case "/se":options.sectors=options.sectors===true?false:true;toastr.success("\uc0ac\uac01\ud615 \ubaa8\ub4dc  "+(options.sectors===true?"on":"off"),"Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");break;case "/bo":options.borders=options.borders===true?false:true;toastr.success("\ubc31\uadf8\ub77c\uc6b4\ub4dc \ub9f5 \ud14c\ub450\ub9ac  "+(options.borders===true?"on":"off"),"Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");
break;case "/sq":options.squareMode=options.squareMode===true?false:true;toastr.success("\uc0ac\uac01\ud615 \ubaa8\ub4dc  "+(options.squareMode===true?"on":"off"),"Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");break;case "/ce":options.cellalpha=options.cellalpha===true?false:true;toastr.success("\uc138\ud3ec\ud22c\uba85\ud654  "+(options.cellalpha===true?"on":"off"),"Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");break;case "/help":toastr.success("/ce - \uc138\ud3ec\ud22c\uba85\ud654 ON or OFF.","Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");
toastr.success("/se - \ubc31\uadf8\ub77c\uc6b4\ub4dc \ub9f5 ON or OFF.","Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");toastr.success("/bo - \ubc31\uadf8\ub77c\uc6b4\ub4dc \ub9f5 \ud14c\ub450\ub9ac ON or off.","Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");toastr.success("/sq  - \uc0ac\uac01\ud615 \ubaa8\ub4dc ON or off.","Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");toastr.success("/status  - \uc11c\ubc84\uc758 \uc0c1\ud0dc\ub97c \ud655\uc778\ud569\ub2c8\ub2e4.","Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");toastr.success("/id  - \ud50c\ub808\uc774\uc5b4\uc758 \uc544\uc774\ub514\ub97c \ud655\uc778\ud569\ub2c8\ub2e4.",
"Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");toastr.success("/kill  - \uc790\uc2e0\uc758 \uc138\ud3ec\ub97c \uc8fd\uc77c\uc218\uc788\uc2b5\ub2c8\ub2e4","Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");toastr.success("/help  -  \uba85\ub839\uc5b4 \ubaa9\ub85d\uc744 \ubd88\ub7ec\uc635\ub2c8\ub2e4","Aqua.Party \uacf5\uc9c0\uc0ac\ud56d");break;default:var buffer=prepareData(2+2*textBox.value.length);var offset=0;buffer.setUint8(offset++,99);buffer.setUint8(offset++,0);for(var i=0;i<textBox.value.length;++i){buffer.setUint16(offset,
textBox.value.charCodeAt(i),true);offset+=2}send(buffer);break}textBox.blur();textBox.value=""}break}};window.setNick=function(arg){$("#overlays").hide();userNickName=arg;sendNickName();userScore=0};window.watch=function(){userNickName=null;isWatching=true;sendUint8(1);$("#overlays").hide()};$("#chat").on("blur",function(){isTyping=false});$("#chat").on("focus",function(){isTyping=true});$("#delay").on("input",function(){$("#animationTxt").text("\ubd84\uc5f4\uac10 : "+$("#delay").val());options.delay=
Number($("#delay").val())});$("#food").change(function(){options.hideFood=$(this).is(":checked")});$("#sqMode").change(function(){options.squareMode=$(this).is(":checked")});$("#cellalpha").change(function(){options.cellalpha=$(this).is(":checked")});$("#ERTP").change(function(){options.ERTP=$(this).is(":checked")});$("#sectors").change(function(){options.sectors=$(this).is(":checked")});$("#borders").change(function(){options.borders=$(this).is(":checked")});$("#name").change(function(){options.noNames=
$(this).is(":checked")});$("#chathi").change(function(){options.chathi=$(this).is(":checked")});$("#mass").change(function(){options.noMass=$(this).is(":checked")});$("#bgColour").change(function(){options.bgColour=$("#bgColour").val()});$("#borderColour").change(function(){options.borderColour=$("#borderColour").val()});$("#sectorColour").change(function(){options.sectorColour=$("#sectorColour").val()});if(playerCells.length===0&&isWatching===false)$("#overlays").fadeIn(600)}
function resetVars(){nodesOnScreen=[];playerCells=[];nodes=[];nodelist=[];Cells=[];leaderboard=[];userScore=0;messages=[]}function connect(url){if(ws)ws.close();ws=new WebSocket(url);ws.binaryType="arraybuffer";ws.onmessage=onWsMessage.bind(this);ws.onopen=onOpen.bind(this);ws.onerror=onError.bind(this);ws.onclose=onClose.bind(this)}
function onOpen(){resetVars();var buffer=prepareData(5);buffer.setUint8(0,254);buffer.setUint32(1,4,true);send(buffer);var buffer=prepareData(5);buffer.setUint8(0,255);buffer.setUint32(1,1332175218,true);send(buffer);console.log("Aqua.Party \uc11c\ubc84\uc5d0 \uc5f0\uacb0\ub418\uc5c8\uc2b5\ub2c8\ub2e4")}function onError(event){console.log(event.code)}
function onClose(){console.log("Aqua.Party \uc11c\ubc84\uac00 \ub2eb\ud614\uc2b5\ub2c8\ub2e4 (\uc11c\ubc84\uc810\uac80\uc911\uc774\uc544\ub2c8\ub77c\uba74 2\ubd84\ud6c4\uc5d0 F5\ub97c\ub20c\ub7ec\uc8fc\uc138\uc694)")}function handleWheel(event){zoom*=Math.pow(.9,event.wheelDelta/-120||event.detail||0)}function onWsMessage(msg){handleMessage(new DataView(msg.data))}function prepareData(data){return new DataView(new ArrayBuffer(data))}function send(data){if(!ws)return;ws.send(data.buffer)}
function handleMessage(msg){function getString(){var text="",char;while((char=msg.getUint16(offset,true))!=0){offset+=2;text+=String.fromCharCode(char)}offset+=2;return text}var offset=0,setCustomLB=false;switch(msg.getUint8(offset++)){case 16:updateNodes(msg,offset);break;case 17:posX=msg.getFloat32(offset,true);offset+=4;posY=msg.getFloat32(offset,true);offset+=4;posSize=msg.getFloat32(offset,true);offset+=4;break;case 20:playerCells=[];nodesOnScreen=[];break;case 32:nodesOnScreen.push(msg.getUint32(offset,
true));offset+=4;break;case 48:setCustomLB=true;noRanking=true;break;case 49:if(!setCustomLB)noRanking=false;var LBplayerNum=msg.getUint32(offset,true);offset+=4;leaderboard=[];for(i=0;i<LBplayerNum;++i){var nodeId=msg.getUint32(offset,true);offset+=4;leaderboard.push({id:nodeId,name:getString()})}break;case 50:teamScores=[];var LBteamNum=msg.getUint32(offset,true);offset+=4;for(var i=0;i<LBteamNum;++i){teamScores.push(msg.getFloat32(offset,true));offset+=4}console.log(teamScores);break;case 64:leftPos=
msg.getFloat64(offset,true);offset+=8;topPos=msg.getFloat64(offset,true);offset+=8;rightPos=msg.getFloat64(offset,true);offset+=8;bottomPos=msg.getFloat64(offset,true);offset+=8;posX=(rightPos+leftPos)/2;posY=(bottomPos+topPos)/2;posSize=1;minX=leftPos;minY=topPos;maxX=rightPos;maxY=bottomPos;if(0==playerCells.length){nodeX=posX;nodeY=posY;viewZoom=posSize}break;case 99:offset++;var r=msg.getUint8(offset++);var g=msg.getUint8(offset++);var b=msg.getUint8(offset++);var color=(r<<16|g<<8|b).toString(16);
while(color.length>6)color="0"+color;color="#"+color;toastr.options={"closeButton":false,"debug":false,"newestOnTop":false,"progressBar":false,"positionClass":"toast-bottom-left","preventDuplicates":false,"onclick":null,"showDuration":"300","hideDuration":"1000","timeOut":"5000","extendedTimeOut":"1000","showEasing":"swing","hideEasing":"linear","showMethod":"fadeIn","hideMethod":"fadeOut"};toastr.success(getString(),getString(),Date.now())}}
function updateNodes(msg,offset){timestamp=+new Date;var code=Math.random();var queueLength=msg.getUint16(offset,true);offset+=2;for(i=0;i<queueLength;++i){var killer=nodes[msg.getUint32(offset,true)],killedNode=nodes[msg.getUint32(offset+4,true)];offset+=8;if(killer&&killedNode){killedNode.destroy();killedNode.ox=killedNode.x;killedNode.oy=killedNode.y;killedNode.oSize=killedNode.size;killedNode.nx=killer.x;killedNode.ny=killer.y;killedNode.nSize=killedNode.size;killedNode.updateTime=timestamp}}while(1){var nodeid=
msg.getUint32(offset,true);offset+=4;if(0==nodeid)break;i++;var size,posY,posX=msg.getInt16(offset,true);offset+=2;posY=msg.getInt16(offset,true);offset+=2;size=msg.getInt16(offset,true);offset+=2;for(var r=msg.getUint8(offset++),g=msg.getUint8(offset++),b=msg.getUint8(offset++),color=(r<<16|g<<8|b).toString(16);6>color.length;)color="0"+color;var colorstr="#"+color,flags=msg.getUint8(offset++),flagVirus=!!(flags&1),flagPlayer=!!(flags&16);flags&2&&(offset+=4);flags&4&&(offset+=8);flags&8&&(offset+=
16);for(var char,name="";;){char=msg.getUint16(offset,true);offset+=2;if(0==char)break;name+=String.fromCharCode(char)}var node=null;if(nodes.hasOwnProperty(nodeid)){node=nodes[nodeid];node.updatePos();node.ox=node.x;node.oy=node.y;node.oSize=node.size;node.color=colorstr}else{node=new Cell(nodeid,posX,posY,size,colorstr,name);nodelist.push(node);nodes[nodeid]=node;node.ka=posX;node.la=posY}node.isVirus=flagVirus;node.isPlayer=flagPlayer;node.nx=posX;node.ny=posY;node.nSize=size;node.updateCode=code;
node.updateTime=timestamp;node.flag=flags;if(-1!=nodesOnScreen.indexOf(nodeid)&&-1==playerCells.indexOf(node)){document.getElementById("overlays").style.display="none";playerCells.push(node);if(1==playerCells.length){nodeX=node.x;nodeY=node.y}}}queueLength=msg.getUint32(offset,true);offset+=4;for(i=0;i<queueLength;i++){var nodeId=msg.getUint32(offset,true);offset+=4;node=nodes[nodeId];null!=node&&node.destroy()}}
function Sectors(){if(options.sectors===true){var x=Math.round(minX)+40;var y=Math.round(minY)+40;var second="ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");var barWidth=(Math.round(maxX)-90-x)/5;var h=(Math.round(maxY)-40-y)/5;var j=0;ctx.save();ctx.beginPath();ctx.lineWidth=.05;ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=barWidth*.7+"px Roboto";ctx.fillStyle="#"+options.sectorColour;while(j<5){var i$0=0;while(5>i$0){ctx.fillText(second[j]+(i$0+1),x+barWidth*i$0+barWidth/2,y+h*j+h/2);i$0++}j++}ctx.lineWidth=
150;ctx.strokeStyle="#1A1A1A";j=0;while(j<5){i=0;while(i<5){ctx.strokeRect(x+barWidth*i,y+h*j,barWidth,h);i++}j++}ctx.stroke();ctx.restore()}}function sendMouseMove(){if(!ws||ws.readyState==ws.OPEN){var buffer=prepareData(21);buffer.setUint8(0,16);buffer.setFloat64(1,X,true);buffer.setFloat64(9,Y,true);buffer.setUint32(17,0,true);send(buffer)}}
function sendNickName(){if(ws.readyState==ws.OPEN&&null!=userNickName){var buffer=prepareData(1+2*userNickName.length);buffer.setUint8(0,0);for(var i=0;i<userNickName.length;++i)buffer.setUint16(1+2*i,userNickName.charCodeAt(i),true);send(buffer)}}function sendUint8(data){if(ws.readyState==ws.OPEN){var buffer=prepareData(1);buffer.setUint8(0,data);send(buffer)}}function reDraw(){Draw();window.requestAnimationFrame(reDraw)}
function canvasResize(){window.scrollTo(0,0);ctx.canvas.width=window.innerWidth;ctx.canvas.height=window.innerHeight;ctx.canvas.width=ctx.canvas.width;ctx.canvas.height=ctx.canvas.height}function hideOverlays(){hasOverlay=false;$("#overlays").hide()}function showOverlays(arg){hasOverlay=true;userNickName=null;$("#overlays").fadeIn(arg?200:3E3)}function viewRange(){var ratio;ratio=Math.max(ctx.canvas.height/1080,ctx.canvas.width/4E3);return ratio*zoom}
function calcViewZoom(){if(0!=playerCells.length){for(var newViewZoom=0,i=0;i<playerCells.length;i++)newViewZoom=Math.pow(Math.min(64/newViewZoom,1),.4)*viewRange();viewZoom=(9*viewZoom+newViewZoom)/10}}
function Draw(){var a,oldtime=Date.now();timestamp=oldtime;if(0<playerCells.length){calcViewZoom();var c=a=0;for(var d=0;d<playerCells.length;d++){playerCells[d].updatePos();a+=playerCells[d].x/playerCells.length;c+=playerCells[d].y/playerCells.length}posX=a;posY=c;posSize=viewZoom;nodeX=(nodeX+a)/2;nodeY=(nodeY+c)/2}else{nodeX=(29*nodeX+posX)/30;nodeY=(29*nodeY+posY)/30;viewZoom=(9*viewZoom+posSize*viewRange())/10}updateMouse();drawBackground();nodelist.sort(function(a,b){return a.size==b.size?a.id-
b.id:a.size-b.size});ctx.save();ctx.translate(ctx.canvas.width/2,ctx.canvas.height/2);ctx.scale(viewZoom,viewZoom);ctx.translate(-nodeX,-nodeY);Sectors();Borders();d=0;while(d<Cells.length){Cells[d].drawOneCell(ctx);d++}d=0;while(d<nodelist.length){nodelist[d].drawOneCell(ctx);d++}ctx.restore();userScore=Math.max(userScore,calcUserScore())/100;var scoreText="\uc138\ud3ec\ud06c\uae30:  "+~~userScore;ctx.globalAlpha=1;ctx.font="20px Tahoma";ctx.fillStyle="#FFF";ctx.fillText(scoreText,10,25);var frames=
fps.getFPS();var fpsText="FPS  : "+frames;if(frames>=40)ctx.fillStyle="#00FF00";else if(frames>=30)ctx.fillStyle="#FFFF33";else ctx.fillStyle="#FF0000";ctx.globalAlpha=1;ctx.font="20px Tahoma";ctx.fillText(fpsText,10,50);for(var i=0;i<leaderboard.length;i++){var section=leaderboard[i];var name=i+1+". "+(section.name===""?"An Unnamed Cell":section.name);ctx.globalAlpha=.8;ctx.font="15px Tahoma";ctx.fillStyle="#FFF";ctx.fillText(name,ctx.canvas.width-200,40+24*i)}if(options.chathi===true)$("#chat").hide();
else $("#chat").show();if(messages.length>=1&&options.chathi===true)messages.splice(0,messages.length);if(messages.length>=20&&options.chathi===false)messages.splice(0,messages.length);for(var i=0;i<messages.length;i++){var message=messages[i];var content=message.content;var author=message.author;ctx.globalAlpha=.9;ctx.font="15px Tahoma";ctx.fillStyle=message.color;ctx.fillText(author+": "+content,ctx.canvas.width/ctx.canvas.height+20,ctx.canvas.height/ctx.canvas.width+ctx.canvas.height-500- -24*
i)}ctx.restore()}function Borders(){if(options.borders===true){ctx.save();ctx.strokeStyle="#"+options.borderColour;ctx.lineWidth=40;ctx.beginPath();ctx.moveTo(minX,minY);ctx.lineTo(maxX,minY);ctx.lineTo(maxX,maxY);ctx.lineTo(minX,maxY);ctx.closePath();ctx.stroke();ctx.restore()}}function drawBackground(){ctx.fillStyle="#"+options.bgColour;ctx.fillRect(0,0,ctx.canvas.width,ctx.canvas.height);ctx.save()}
function calcUserScore(){for(var score=0,i=0;i<playerCells.length;i++)score+=playerCells[i].nSize*playerCells[i].nSize;return score}function AddMessage(author,color,content,time){messages.push({author:author,color:color,content:content,time:time})}function Cell(id,x,y,size,color,name){this.id=id;this.ox=this.x=x;this.oy=this.y=y;this.oSize=size;this.size=size;this.color=color;this.name=name}
Cell.prototype={id:0,name:null,x:0,y:0,size:0,ox:0,oy:0,oSize:0,nx:0,ny:0,nSize:0,flag:0,updateTime:0,updateCode:0,delay:0,destroyed:false,isVirus:false,destroy:function(){var tmp;for(tmp=0;tmp<nodelist.length;tmp++)if(nodelist[tmp]==this){nodelist.splice(tmp,1);break}delete nodes[this.id];tmp=playerCells.indexOf(this);if(-1!=tmp)playerCells.splice(tmp,1);tmp=nodesOnScreen.indexOf(this.id);if(-1!=tmp)nodesOnScreen.splice(tmp,1);this.destroyed=true;Cells.push(this)},updatePos:function(){if(0==this.id)return 1;
var a;a=(timestamp-this.updateTime)/options.delay;a=0>a?0:1<a?1:a;var b=0>a?0:1<a?1:a;if(this.destroyed&&1<=b){var c=Cells.indexOf(this);-1!=c&&Cells.splice(c,1)}this.x=a*(this.nx-this.ox)+this.ox;this.y=a*(this.ny-this.oy)+this.oy;this.size=b*(this.nSize-this.oSize)+this.oSize;return b},drawOneCell:function(ctx){var mass=~~(this.size*this.size/100);var isFood=!this.isVirus&&mass<5;if(options.hideFood===true&&isFood)return;ctx.save();c=this.updatePos();this.destroyed&&(ctx.globalAlpha*=1-c);ctx.lineWidth=
10;ctx.fillStyle=this.color;ctx.beginPath();if(this.isVirus)ctx.globalAlpha=.6;if(options.squareMode===true)ctx.rect(this.x-this.size,this.y-this.size,this.size*2,this.size*2);else ctx.arc(this.x,this.y,this.size,.1,Math.PI*2,false);if(options.cellalpha===true)ctx.globalAlpha=.6;ctx.closePath();ctx.fill();if(-1!=playerCells.indexOf(this)){var skin=new Image;var skinUrl=String($("#skinUrl").val());if(skinUrl.substr(0,20)==="http://i.imgur.com/","https://i.imgur.com/")skin.src=skinUrl;ctx.save();ctx.clip();
ctx.drawImage(skin,this.x-this.size,this.y-this.size,this.size*2,this.size*2);ctx.restore()}if(0!=this.id){ctx.strokeStyle=this.color;ctx.globalAlpha=.6;ctx.stroke();if(this.name&&mass>=200&&options.noNames===false){ctx.globalAlpha=1;ctx.font=Math.max(~~(.3*this.size),24)+"px Roboto";ctx.fillStyle="#FFFFFF";ctx.textAlign="center";ctx.fillText(this.name,this.x,this.y)}if(mass>=200&&options.noMass===false){ctx.globalAlpha=1;ctx.font=Math.max(~~(.2*this.size),24)+"px Roboto";ctx.fillStyle="#FFFFFF";
ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(mass,this.x,this.y+90)}}ctx.restore()}};Main();setInterval(updateWindowFunctions,100); if(!window.jscolor)window.jscolor=function(){var jsc={register:function(){jsc.attachDOMReadyEvent(jsc.init);jsc.attachEvent(document,"mousedown",jsc.onDocumentMouseDown);jsc.attachEvent(document,"touchstart",jsc.onDocumentTouchStart);jsc.attachEvent(window,"resize",jsc.onWindowResize)},init:function(){if(jsc.jscolor.lookupClass)jsc.jscolor.installByClassName(jsc.jscolor.lookupClass)},tryInstallOnElements:function(elms,className){var matchClass=new RegExp("(^|\\s)("+className+")(\\s*(\\{[^}]*\\})|\\s|$)",
"i");for(var i=0;i<elms.length;i+=1){if(elms[i].type!==undefined&&elms[i].type.toLowerCase()=="color")if(jsc.isColorAttrSupported)continue;var m;if(!elms[i].jscolor&&elms[i].className&&(m=elms[i].className.match(matchClass))){var targetElm=elms[i];var optsStr=null;var dataOptions=jsc.getDataAttr(targetElm,"jscolor");if(dataOptions!==null)optsStr=dataOptions;else if(m[4])optsStr=m[4];var opts={};if(optsStr)try{opts=(new Function("return ("+optsStr+")"))()}catch(eParseError){jsc.warn("Error parsing jscolor options: "+
eParseError+":\n"+optsStr)}targetElm.jscolor=new jsc.jscolor(targetElm,opts)}}},isColorAttrSupported:function(){var elm=document.createElement("input");if(elm.setAttribute){elm.setAttribute("type","color");if(elm.type.toLowerCase()=="color")return true}return false}(),isCanvasSupported:function(){var elm=document.createElement("canvas");return!!(elm.getContext&&elm.getContext("2d"))}(),fetchElement:function(mixed){return typeof mixed==="string"?document.getElementById(mixed):mixed},isElementType:function(elm,
type){return elm.nodeName.toLowerCase()===type.toLowerCase()},getDataAttr:function(el,name){var attrName="data-"+name;var attrValue=el.getAttribute(attrName);if(attrValue!==null)return attrValue;return null},attachEvent:function(el,evnt,func){if(el.addEventListener)el.addEventListener(evnt,func,false);else if(el.attachEvent)el.attachEvent("on"+evnt,func)},detachEvent:function(el,evnt,func){if(el.removeEventListener)el.removeEventListener(evnt,func,false);else if(el.detachEvent)el.detachEvent("on"+
evnt,func)},_attachedGroupEvents:{},attachGroupEvent:function(groupName,el,evnt,func){if(!jsc._attachedGroupEvents.hasOwnProperty(groupName))jsc._attachedGroupEvents[groupName]=[];jsc._attachedGroupEvents[groupName].push([el,evnt,func]);jsc.attachEvent(el,evnt,func)},detachGroupEvents:function(groupName){if(jsc._attachedGroupEvents.hasOwnProperty(groupName)){for(var i=0;i<jsc._attachedGroupEvents[groupName].length;i+=1){var evt=jsc._attachedGroupEvents[groupName][i];jsc.detachEvent(evt[0],evt[1],
evt[2])}delete jsc._attachedGroupEvents[groupName]}},attachDOMReadyEvent:function(func){var fired=false;var fireOnce=function(){if(!fired){fired=true;func()}};if(document.readyState==="complete"){setTimeout(fireOnce,1);return}if(document.addEventListener){document.addEventListener("DOMContentLoaded",fireOnce,false);window.addEventListener("load",fireOnce,false)}else if(document.attachEvent){document.attachEvent("onreadystatechange",function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",
arguments.callee);fireOnce()}});window.attachEvent("onload",fireOnce);if(document.documentElement.doScroll&&window==window.top){var tryScroll=function(){if(!document.body)return;try{document.documentElement.doScroll("left");fireOnce()}catch(e){setTimeout(tryScroll,1)}};tryScroll()}}},warn:function(msg){if(window.console&&window.console.warn)window.console.warn(msg)},preventDefault:function(e){if(e.preventDefault)e.preventDefault();e.returnValue=false},captureTarget:function(target){if(target.setCapture){jsc._capturedTarget=
target;jsc._capturedTarget.setCapture()}},releaseTarget:function(){if(jsc._capturedTarget){jsc._capturedTarget.releaseCapture();jsc._capturedTarget=null}},fireEvent:function(el,evnt){if(!el)return;if(document.createEvent){var ev=document.createEvent("HTMLEvents");ev.initEvent(evnt,true,true);el.dispatchEvent(ev)}else if(document.createEventObject){var ev=document.createEventObject();el.fireEvent("on"+evnt,ev)}else if(el["on"+evnt])el["on"+evnt]()},classNameToList:function(className){return className.replace(/^\s+|\s+$/g,
"").split(/\s+/)},hasClass:function(elm,className){if(!className)return false;return-1!=(" "+elm.className.replace(/\s+/g," ")+" ").indexOf(" "+className+" ")},setClass:function(elm,className){var classList=jsc.classNameToList(className);for(var i=0;i<classList.length;i+=1)if(!jsc.hasClass(elm,classList[i]))elm.className+=(elm.className?" ":"")+classList[i]},unsetClass:function(elm,className){var classList=jsc.classNameToList(className);for(var i=0;i<classList.length;i+=1){var repl=new RegExp("^\\s*"+
classList[i]+"\\s*|"+"\\s*"+classList[i]+"\\s*$|"+"\\s+"+classList[i]+"(\\s+)","g");elm.className=elm.className.replace(repl,"$1")}},getStyle:function(elm){return window.getComputedStyle?window.getComputedStyle(elm):elm.currentStyle},setStyle:function(){var helper=document.createElement("div");var getSupportedProp=function(names){for(var i=0;i<names.length;i+=1)if(names[i]in helper.style)return names[i]};var props={borderRadius:getSupportedProp(["borderRadius","MozBorderRadius","webkitBorderRadius"]),
boxShadow:getSupportedProp(["boxShadow","MozBoxShadow","webkitBoxShadow"])};return function(elm,prop,value){switch(prop.toLowerCase()){case "opacity":var alphaOpacity=Math.round(parseFloat(value)*100);elm.style.opacity=value;elm.style.filter="alpha(opacity="+alphaOpacity+")";break;default:elm.style[props[prop]]=value;break}}}(),setBorderRadius:function(elm,value){jsc.setStyle(elm,"borderRadius",value||"0")},setBoxShadow:function(elm,value){jsc.setStyle(elm,"boxShadow",value||"none")},getElementPos:function(e,
relativeToViewport){var x=0,y=0;var rect=e.getBoundingClientRect();x=rect.left;y=rect.top;if(!relativeToViewport){var viewPos=jsc.getViewPos();x+=viewPos[0];y+=viewPos[1]}return[x,y]},getElementSize:function(e){return[e.offsetWidth,e.offsetHeight]},getAbsPointerPos:function(e){if(!e)e=window.event;var x=0,y=0;if(typeof e.changedTouches!=="undefined"&&e.changedTouches.length){x=e.changedTouches[0].clientX;y=e.changedTouches[0].clientY}else if(typeof e.clientX==="number"){x=e.clientX;y=e.clientY}return{x:x,
y:y}},getRelPointerPos:function(e){if(!e)e=window.event;var target=e.target||e.srcElement;var targetRect=target.getBoundingClientRect();var x=0,y=0;var clientX=0,clientY=0;if(typeof e.changedTouches!=="undefined"&&e.changedTouches.length){clientX=e.changedTouches[0].clientX;clientY=e.changedTouches[0].clientY}else if(typeof e.clientX==="number"){clientX=e.clientX;clientY=e.clientY}x=clientX-targetRect.left;y=clientY-targetRect.top;return{x:x,y:y}},getViewPos:function(){var doc=document.documentElement;
return[(window.pageXOffset||doc.scrollLeft)-(doc.clientLeft||0),(window.pageYOffset||doc.scrollTop)-(doc.clientTop||0)]},getViewSize:function(){var doc=document.documentElement;return[window.innerWidth||doc.clientWidth,window.innerHeight||doc.clientHeight]},redrawPosition:function(){if(jsc.picker&&jsc.picker.owner){var thisObj=jsc.picker.owner;var tp,vp;if(thisObj.fixed){tp=jsc.getElementPos(thisObj.targetElement,true);vp=[0,0]}else{tp=jsc.getElementPos(thisObj.targetElement);vp=jsc.getViewPos()}var ts=
jsc.getElementSize(thisObj.targetElement);var vs=jsc.getViewSize();var ps=jsc.getPickerOuterDims(thisObj);var a,b,c;switch(thisObj.position.toLowerCase()){case "left":a=1;b=0;c=-1;break;case "right":a=1;b=0;c=1;break;case "top":a=0;b=1;c=-1;break;default:a=0;b=1;c=1;break}var l=(ts[b]+ps[b])/2;if(!thisObj.smartPosition)var pp=[tp[a],tp[b]+ts[b]-l+l*c];else var pp=[-vp[a]+tp[a]+ps[a]>vs[a]?-vp[a]+tp[a]+ts[a]/2>vs[a]/2&&tp[a]+ts[a]-ps[a]>=0?tp[a]+ts[a]-ps[a]:tp[a]:tp[a],-vp[b]+tp[b]+ts[b]+ps[b]-l+l*
c>vs[b]?-vp[b]+tp[b]+ts[b]/2>vs[b]/2&&tp[b]+ts[b]-l-l*c>=0?tp[b]+ts[b]-l-l*c:tp[b]+ts[b]-l+l*c:tp[b]+ts[b]-l+l*c>=0?tp[b]+ts[b]-l+l*c:tp[b]+ts[b]-l-l*c];var x=pp[a];var y=pp[b];var positionValue=thisObj.fixed?"fixed":"absolute";var contractShadow=(pp[0]+ps[0]>tp[0]||pp[0]<tp[0]+ts[0])&&pp[1]+ps[1]<tp[1]+ts[1];jsc._drawPosition(thisObj,x,y,positionValue,contractShadow)}},_drawPosition:function(thisObj,x,y,positionValue,contractShadow){var vShadow=contractShadow?0:thisObj.shadowBlur;jsc.picker.wrap.style.position=
positionValue;jsc.picker.wrap.style.left=x+"px";jsc.picker.wrap.style.top=y+"px";jsc.setBoxShadow(jsc.picker.boxS,thisObj.shadow?new jsc.BoxShadow(0,vShadow,thisObj.shadowBlur,0,thisObj.shadowColor):null)},getPickerDims:function(thisObj){var displaySlider=!!jsc.getSliderComponent(thisObj);var dims=[2*thisObj.insetWidth+2*thisObj.padding+thisObj.width+(displaySlider?2*thisObj.insetWidth+jsc.getPadToSliderPadding(thisObj)+thisObj.sliderSize:0),2*thisObj.insetWidth+2*thisObj.padding+thisObj.height+(thisObj.closable?
2*thisObj.insetWidth+thisObj.padding+thisObj.buttonHeight:0)];return dims},getPickerOuterDims:function(thisObj){var dims=jsc.getPickerDims(thisObj);return[dims[0]+2*thisObj.borderWidth,dims[1]+2*thisObj.borderWidth]},getPadToSliderPadding:function(thisObj){return Math.max(thisObj.padding,1.5*(2*thisObj.pointerBorderWidth+thisObj.pointerThickness))},getPadYComponent:function(thisObj){switch(thisObj.mode.charAt(1).toLowerCase()){case "v":return"v";break}return"s"},getSliderComponent:function(thisObj){if(thisObj.mode.length>
2)switch(thisObj.mode.charAt(2).toLowerCase()){case "s":return"s";break;case "v":return"v";break}return null},onDocumentMouseDown:function(e){if(!e)e=window.event;var target=e.target||e.srcElement;if(target._jscLinkedInstance){if(target._jscLinkedInstance.showOnClick)target._jscLinkedInstance.show()}else if(target._jscControlName)jsc.onControlPointerStart(e,target,target._jscControlName,"mouse");else if(jsc.picker&&jsc.picker.owner)jsc.picker.owner.hide()},onDocumentTouchStart:function(e){if(!e)e=
window.event;var target=e.target||e.srcElement;if(target._jscLinkedInstance){if(target._jscLinkedInstance.showOnClick)target._jscLinkedInstance.show()}else if(target._jscControlName)jsc.onControlPointerStart(e,target,target._jscControlName,"touch");else if(jsc.picker&&jsc.picker.owner)jsc.picker.owner.hide()},onWindowResize:function(e){jsc.redrawPosition()},onParentScroll:function(e){if(jsc.picker&&jsc.picker.owner)jsc.picker.owner.hide()},_pointerMoveEvent:{mouse:"mousemove",touch:"touchmove"},_pointerEndEvent:{mouse:"mouseup",
touch:"touchend"},_pointerOrigin:null,_capturedTarget:null,onControlPointerStart:function(e,target,controlName,pointerType){var thisObj=target._jscInstance;jsc.preventDefault(e);jsc.captureTarget(target);var registerDragEvents=function(doc,offset){jsc.attachGroupEvent("drag",doc,jsc._pointerMoveEvent[pointerType],jsc.onDocumentPointerMove(e,target,controlName,pointerType,offset));jsc.attachGroupEvent("drag",doc,jsc._pointerEndEvent[pointerType],jsc.onDocumentPointerEnd(e,target,controlName,pointerType))};
registerDragEvents(document,[0,0]);if(window.parent&&window.frameElement){var rect=window.frameElement.getBoundingClientRect();var ofs=[-rect.left,-rect.top];registerDragEvents(window.parent.window.document,ofs)}var abs=jsc.getAbsPointerPos(e);var rel=jsc.getRelPointerPos(e);jsc._pointerOrigin={x:abs.x-rel.x,y:abs.y-rel.y};switch(controlName){case "pad":switch(jsc.getSliderComponent(thisObj)){case "s":if(thisObj.hsv[1]===0)thisObj.fromHSV(null,100,null);break;case "v":if(thisObj.hsv[2]===0)thisObj.fromHSV(null,
null,100);break}jsc.setPad(thisObj,e,0,0);break;case "sld":jsc.setSld(thisObj,e,0);break}jsc.dispatchFineChange(thisObj)},onDocumentPointerMove:function(e,target,controlName,pointerType,offset){return function(e){var thisObj=target._jscInstance;switch(controlName){case "pad":if(!e)e=window.event;jsc.setPad(thisObj,e,offset[0],offset[1]);jsc.dispatchFineChange(thisObj);break;case "sld":if(!e)e=window.event;jsc.setSld(thisObj,e,offset[1]);jsc.dispatchFineChange(thisObj);break}}},onDocumentPointerEnd:function(e,
target,controlName,pointerType){return function(e){var thisObj=target._jscInstance;jsc.detachGroupEvents("drag");jsc.releaseTarget();jsc.dispatchChange(thisObj)}},dispatchChange:function(thisObj){if(thisObj.valueElement)if(jsc.isElementType(thisObj.valueElement,"input"))jsc.fireEvent(thisObj.valueElement,"change")},dispatchFineChange:function(thisObj){if(thisObj.onFineChange){var callback;if(typeof thisObj.onFineChange==="string")callback=new Function(thisObj.onFineChange);else callback=thisObj.onFineChange;
callback.call(thisObj)}},setPad:function(thisObj,e,ofsX,ofsY){var pointerAbs=jsc.getAbsPointerPos(e);var x=ofsX+pointerAbs.x-jsc._pointerOrigin.x-thisObj.padding-thisObj.insetWidth;var y=ofsY+pointerAbs.y-jsc._pointerOrigin.y-thisObj.padding-thisObj.insetWidth;var xVal=x*(360/(thisObj.width-1));var yVal=100-y*(100/(thisObj.height-1));switch(jsc.getPadYComponent(thisObj)){case "s":thisObj.fromHSV(xVal,yVal,null,jsc.leaveSld);break;case "v":thisObj.fromHSV(xVal,null,yVal,jsc.leaveSld);break}},setSld:function(thisObj,
e,ofsY){var pointerAbs=jsc.getAbsPointerPos(e);var y=ofsY+pointerAbs.y-jsc._pointerOrigin.y-thisObj.padding-thisObj.insetWidth;var yVal=100-y*(100/(thisObj.height-1));switch(jsc.getSliderComponent(thisObj)){case "s":thisObj.fromHSV(null,yVal,null,jsc.leavePad);break;case "v":thisObj.fromHSV(null,null,yVal,jsc.leavePad);break}},_vmlNS:"jsc_vml_",_vmlCSS:"jsc_vml_css_",_vmlReady:false,initVML:function(){if(!jsc._vmlReady){var doc=document;if(!doc.namespaces[jsc._vmlNS])doc.namespaces.add(jsc._vmlNS,
"urn:schemas-microsoft-com:vml");if(!doc.styleSheets[jsc._vmlCSS]){var tags=["shape","shapetype","group","background","path","formulas","handles","fill","stroke","shadow","textbox","textpath","imagedata","line","polyline","curve","rect","roundrect","oval","arc","image"];var ss=doc.createStyleSheet();ss.owningElement.id=jsc._vmlCSS;for(var i=0;i<tags.length;i+=1)ss.addRule(jsc._vmlNS+"\\:"+tags[i],"behavior:url(#default#VML);")}jsc._vmlReady=true}},createPalette:function(){var paletteObj={elm:null,
draw:null};if(jsc.isCanvasSupported){var canvas=document.createElement("canvas");var ctx=canvas.getContext("2d");var drawFunc=function(width,height,type){canvas.width=width;canvas.height=height;ctx.clearRect(0,0,canvas.width,canvas.height);var hGrad=ctx.createLinearGradient(0,0,canvas.width,0);hGrad.addColorStop(0/6,"#F00");hGrad.addColorStop(1/6,"#FF0");hGrad.addColorStop(2/6,"#0F0");hGrad.addColorStop(3/6,"#0FF");hGrad.addColorStop(4/6,"#00F");hGrad.addColorStop(5/6,"#F0F");hGrad.addColorStop(6/
6,"#F00");ctx.fillStyle=hGrad;ctx.fillRect(0,0,canvas.width,canvas.height);var vGrad=ctx.createLinearGradient(0,0,0,canvas.height);switch(type.toLowerCase()){case "s":vGrad.addColorStop(0,"rgba(255,255,255,0)");vGrad.addColorStop(1,"rgba(255,255,255,1)");break;case "v":vGrad.addColorStop(0,"rgba(0,0,0,0)");vGrad.addColorStop(1,"rgba(0,0,0,1)");break}ctx.fillStyle=vGrad;ctx.fillRect(0,0,canvas.width,canvas.height)};paletteObj.elm=canvas;paletteObj.draw=drawFunc}else{jsc.initVML();var vmlContainer=
document.createElement("div");vmlContainer.style.position="relative";vmlContainer.style.overflow="hidden";var hGrad=document.createElement(jsc._vmlNS+":fill");hGrad.type="gradient";hGrad.method="linear";hGrad.angle="90";hGrad.colors="16.67% #F0F, 33.33% #00F, 50% #0FF, 66.67% #0F0, 83.33% #FF0";var hRect=document.createElement(jsc._vmlNS+":rect");hRect.style.position="absolute";hRect.style.left=-1+"px";hRect.style.top=-1+"px";hRect.stroked=false;hRect.appendChild(hGrad);vmlContainer.appendChild(hRect);
var vGrad=document.createElement(jsc._vmlNS+":fill");vGrad.type="gradient";vGrad.method="linear";vGrad.angle="180";vGrad.opacity="0";var vRect=document.createElement(jsc._vmlNS+":rect");vRect.style.position="absolute";vRect.style.left=-1+"px";vRect.style.top=-1+"px";vRect.stroked=false;vRect.appendChild(vGrad);vmlContainer.appendChild(vRect);var drawFunc=function(width,height,type){vmlContainer.style.width=width+"px";vmlContainer.style.height=height+"px";hRect.style.width=vRect.style.width=width+
1+"px";hRect.style.height=vRect.style.height=height+1+"px";hGrad.color="#F00";hGrad.color2="#F00";switch(type.toLowerCase()){case "s":vGrad.color=vGrad.color2="#FFF";break;case "v":vGrad.color=vGrad.color2="#000";break}};paletteObj.elm=vmlContainer;paletteObj.draw=drawFunc}return paletteObj},createSliderGradient:function(){var sliderObj={elm:null,draw:null};if(jsc.isCanvasSupported){var canvas=document.createElement("canvas");var ctx=canvas.getContext("2d");var drawFunc=function(width,height,color1,
color2){canvas.width=width;canvas.height=height;ctx.clearRect(0,0,canvas.width,canvas.height);var grad=ctx.createLinearGradient(0,0,0,canvas.height);grad.addColorStop(0,color1);grad.addColorStop(1,color2);ctx.fillStyle=grad;ctx.fillRect(0,0,canvas.width,canvas.height)};sliderObj.elm=canvas;sliderObj.draw=drawFunc}else{jsc.initVML();var vmlContainer=document.createElement("div");vmlContainer.style.position="relative";vmlContainer.style.overflow="hidden";var grad=document.createElement(jsc._vmlNS+":fill");
grad.type="gradient";grad.method="linear";grad.angle="180";var rect=document.createElement(jsc._vmlNS+":rect");rect.style.position="absolute";rect.style.left=-1+"px";rect.style.top=-1+"px";rect.stroked=false;rect.appendChild(grad);vmlContainer.appendChild(rect);var drawFunc=function(width,height,color1,color2){vmlContainer.style.width=width+"px";vmlContainer.style.height=height+"px";rect.style.width=width+1+"px";rect.style.height=height+1+"px";grad.color=color1;grad.color2=color2};sliderObj.elm=vmlContainer;
sliderObj.draw=drawFunc}return sliderObj},leaveValue:1<<0,leaveStyle:1<<1,leavePad:1<<2,leaveSld:1<<3,BoxShadow:function(){var BoxShadow=function(hShadow,vShadow,blur,spread,color,inset){this.hShadow=hShadow;this.vShadow=vShadow;this.blur=blur;this.spread=spread;this.color=color;this.inset=!!inset};BoxShadow.prototype.toString=function(){var vals=[Math.round(this.hShadow)+"px",Math.round(this.vShadow)+"px",Math.round(this.blur)+"px",Math.round(this.spread)+"px",this.color];if(this.inset)vals.push("inset");
return vals.join(" ")};return BoxShadow}(),jscolor:function(targetElement,options){this.value=null;this.valueElement=targetElement;this.styleElement=targetElement;this.required=true;this.refine=true;this.hash=false;this.uppercase=true;this.onFineChange=null;this.activeClass="jscolor-active";this.minS=0;this.maxS=100;this.minV=0;this.maxV=100;this.hsv=[0,0,100];this.rgb=[255,255,255];this.width=181;this.height=101;this.showOnClick=true;this.mode="HSV";this.position="bottom";this.smartPosition=true;
this.sliderSize=16;this.crossSize=8;this.closable=false;this.closeText="Close";this.buttonColor="#000000";this.buttonHeight=18;this.padding=12;this.backgroundColor="#FFFFFF";this.borderWidth=1;this.borderColor="#BBBBBB";this.borderRadius=8;this.insetWidth=1;this.insetColor="#BBBBBB";this.shadow=true;this.shadowBlur=15;this.shadowColor="rgba(0,0,0,0.2)";this.pointerColor="#4C4C4C";this.pointerBorderColor="#FFFFFF";this.pointerBorderWidth=1;this.pointerThickness=2;this.zIndex=1E3;this.container=null;
for(var opt in options)if(options.hasOwnProperty(opt))this[opt]=options[opt];this.hide=function(){if(isPickerOwner())detachPicker()};this.show=function(){drawPicker()};this.redraw=function(){if(isPickerOwner())drawPicker()};this.importColor=function(){if(!this.valueElement)this.exportColor();else if(jsc.isElementType(this.valueElement,"input"))if(!this.refine){if(!this.fromString(this.valueElement.value,jsc.leaveValue)){if(this.styleElement){this.styleElement.style.backgroundImage=this.styleElement._jscOrigStyle.backgroundImage;
this.styleElement.style.backgroundColor=this.styleElement._jscOrigStyle.backgroundColor;this.styleElement.style.color=this.styleElement._jscOrigStyle.color}this.exportColor(jsc.leaveValue|jsc.leaveStyle)}}else if(!this.required&&/^\s*$/.test(this.valueElement.value)){this.valueElement.value="";if(this.styleElement){this.styleElement.style.backgroundImage=this.styleElement._jscOrigStyle.backgroundImage;this.styleElement.style.backgroundColor=this.styleElement._jscOrigStyle.backgroundColor;this.styleElement.style.color=
this.styleElement._jscOrigStyle.color}this.exportColor(jsc.leaveValue|jsc.leaveStyle)}else if(this.fromString(this.valueElement.value));else this.exportColor();else this.exportColor()};this.exportColor=function(flags){if(!(flags&jsc.leaveValue)&&this.valueElement){var value=this.toString();if(this.uppercase)value=value.toUpperCase();if(this.hash)value="#"+value;if(jsc.isElementType(this.valueElement,"input"))this.valueElement.value=value;else this.valueElement.innerHTML=value}if(!(flags&jsc.leaveStyle))if(this.styleElement){this.styleElement.style.backgroundImage=
"none";this.styleElement.style.backgroundColor="#"+this.toString();this.styleElement.style.color=this.isLight()?"#000":"#FFF"}if(!(flags&jsc.leavePad)&&isPickerOwner())redrawPad();if(!(flags&jsc.leaveSld)&&isPickerOwner())redrawSld()};this.fromHSV=function(h,s,v,flags){if(h!==null){if(isNaN(h))return false;h=Math.max(0,Math.min(360,h))}if(s!==null){if(isNaN(s))return false;s=Math.max(0,Math.min(100,this.maxS,s),this.minS)}if(v!==null){if(isNaN(v))return false;v=Math.max(0,Math.min(100,this.maxV,v),
this.minV)}this.rgb=HSV_RGB(h===null?this.hsv[0]:this.hsv[0]=h,s===null?this.hsv[1]:this.hsv[1]=s,v===null?this.hsv[2]:this.hsv[2]=v);this.exportColor(flags)};this.fromRGB=function(r,g,b,flags){if(r!==null){if(isNaN(r))return false;r=Math.max(0,Math.min(255,r))}if(g!==null){if(isNaN(g))return false;g=Math.max(0,Math.min(255,g))}if(b!==null){if(isNaN(b))return false;b=Math.max(0,Math.min(255,b))}var hsv=RGB_HSV(r===null?this.rgb[0]:r,g===null?this.rgb[1]:g,b===null?this.rgb[2]:b);if(hsv[0]!==null)this.hsv[0]=
Math.max(0,Math.min(360,hsv[0]));if(hsv[2]!==0)this.hsv[1]=hsv[1]===null?null:Math.max(0,this.minS,Math.min(100,this.maxS,hsv[1]));this.hsv[2]=hsv[2]===null?null:Math.max(0,this.minV,Math.min(100,this.maxV,hsv[2]));var rgb=HSV_RGB(this.hsv[0],this.hsv[1],this.hsv[2]);this.rgb[0]=rgb[0];this.rgb[1]=rgb[1];this.rgb[2]=rgb[2];this.exportColor(flags)};this.fromString=function(str,flags){var m;if(m=str.match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i)){if(m[1].length===6)this.fromRGB(parseInt(m[1].substr(0,
2),16),parseInt(m[1].substr(2,2),16),parseInt(m[1].substr(4,2),16),flags);else this.fromRGB(parseInt(m[1].charAt(0)+m[1].charAt(0),16),parseInt(m[1].charAt(1)+m[1].charAt(1),16),parseInt(m[1].charAt(2)+m[1].charAt(2),16),flags);return true}else if(m=str.match(/^\W*rgba?\(([^)]*)\)\W*$/i)){var params=m[1].split(",");var re=/^\s*(\d*)(\.\d+)?\s*$/;var mR,mG,mB;if(params.length>=3&&(mR=params[0].match(re))&&(mG=params[1].match(re))&&(mB=params[2].match(re))){var r=parseFloat((mR[1]||"0")+(mR[2]||""));
var g=parseFloat((mG[1]||"0")+(mG[2]||""));var b=parseFloat((mB[1]||"0")+(mB[2]||""));this.fromRGB(r,g,b,flags);return true}}return false};this.toString=function(){return(256|Math.round(this.rgb[0])).toString(16).substr(1)+(256|Math.round(this.rgb[1])).toString(16).substr(1)+(256|Math.round(this.rgb[2])).toString(16).substr(1)};this.toHEXString=function(){return"#"+this.toString().toUpperCase()};this.toRGBString=function(){return"rgb("+Math.round(this.rgb[0])+","+Math.round(this.rgb[1])+","+Math.round(this.rgb[2])+
")"};this.isLight=function(){return.213*this.rgb[0]+.715*this.rgb[1]+.072*this.rgb[2]>255/2};this._processParentElementsInDOM=function(){if(this._linkedElementsProcessed)return;this._linkedElementsProcessed=true;var elm=this.targetElement;do{var currStyle=jsc.getStyle(elm);if(currStyle&&currStyle.position.toLowerCase()==="fixed")this.fixed=true;if(elm!==this.targetElement)if(!elm._jscEventsAttached){jsc.attachEvent(elm,"scroll",jsc.onParentScroll);elm._jscEventsAttached=true}}while((elm=elm.parentNode)&&
!jsc.isElementType(elm,"body"))};function RGB_HSV(r,g,b){r/=255;g/=255;b/=255;var n=Math.min(Math.min(r,g),b);var v=Math.max(Math.max(r,g),b);var m=v-n;if(m===0)return[null,0,100*v];var h=r===n?3+(b-g)/m:g===n?5+(r-b)/m:1+(g-r)/m;return[60*(h===6?0:h),100*(m/v),100*v]}function HSV_RGB(h,s,v){var u=255*(v/100);if(h===null)return[u,u,u];h/=60;s/=100;var i=Math.floor(h);var f=i%2?h-i:1-(h-i);var m=u*(1-s);var n=u*(1-s*f);switch(i){case 6:case 0:return[u,n,m];case 1:return[n,u,m];case 2:return[m,u,n];
case 3:return[m,n,u];case 4:return[n,m,u];case 5:return[u,m,n]}}function detachPicker(){jsc.unsetClass(THIS.targetElement,THIS.activeClass);jsc.picker.wrap.parentNode.removeChild(jsc.picker.wrap);delete jsc.picker.owner}function drawPicker(){THIS._processParentElementsInDOM();if(!jsc.picker){jsc.picker={owner:null,wrap:document.createElement("div"),box:document.createElement("div"),boxS:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),
padM:document.createElement("div"),padPal:jsc.createPalette(),cross:document.createElement("div"),crossBY:document.createElement("div"),crossBX:document.createElement("div"),crossLY:document.createElement("div"),crossLX:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),sldM:document.createElement("div"),sldGrad:jsc.createSliderGradient(),sldPtrS:document.createElement("div"),sldPtrIB:document.createElement("div"),sldPtrMB:document.createElement("div"),
sldPtrOB:document.createElement("div"),btn:document.createElement("div"),btnT:document.createElement("span")};jsc.picker.pad.appendChild(jsc.picker.padPal.elm);jsc.picker.padB.appendChild(jsc.picker.pad);jsc.picker.cross.appendChild(jsc.picker.crossBY);jsc.picker.cross.appendChild(jsc.picker.crossBX);jsc.picker.cross.appendChild(jsc.picker.crossLY);jsc.picker.cross.appendChild(jsc.picker.crossLX);jsc.picker.padB.appendChild(jsc.picker.cross);jsc.picker.box.appendChild(jsc.picker.padB);jsc.picker.box.appendChild(jsc.picker.padM);
jsc.picker.sld.appendChild(jsc.picker.sldGrad.elm);jsc.picker.sldB.appendChild(jsc.picker.sld);jsc.picker.sldB.appendChild(jsc.picker.sldPtrOB);jsc.picker.sldPtrOB.appendChild(jsc.picker.sldPtrMB);jsc.picker.sldPtrMB.appendChild(jsc.picker.sldPtrIB);jsc.picker.sldPtrIB.appendChild(jsc.picker.sldPtrS);jsc.picker.box.appendChild(jsc.picker.sldB);jsc.picker.box.appendChild(jsc.picker.sldM);jsc.picker.btn.appendChild(jsc.picker.btnT);jsc.picker.box.appendChild(jsc.picker.btn);jsc.picker.boxB.appendChild(jsc.picker.box);
jsc.picker.wrap.appendChild(jsc.picker.boxS);jsc.picker.wrap.appendChild(jsc.picker.boxB)}var p=jsc.picker;var displaySlider=!!jsc.getSliderComponent(THIS);var dims=jsc.getPickerDims(THIS);var crossOuterSize=2*THIS.pointerBorderWidth+THIS.pointerThickness+2*THIS.crossSize;var padToSliderPadding=jsc.getPadToSliderPadding(THIS);var borderRadius=Math.min(THIS.borderRadius,Math.round(THIS.padding*Math.PI));var padCursor="crosshair";p.wrap.style.clear="both";p.wrap.style.width=dims[0]+2*THIS.borderWidth+
"px";p.wrap.style.height=dims[1]+2*THIS.borderWidth+"px";p.wrap.style.zIndex=THIS.zIndex;p.box.style.width=dims[0]+"px";p.box.style.height=dims[1]+"px";p.boxS.style.position="absolute";p.boxS.style.left="0";p.boxS.style.top="0";p.boxS.style.width="100%";p.boxS.style.height="100%";jsc.setBorderRadius(p.boxS,borderRadius+"px");p.boxB.style.position="relative";p.boxB.style.border=THIS.borderWidth+"px solid";p.boxB.style.borderColor=THIS.borderColor;p.boxB.style.background=THIS.backgroundColor;jsc.setBorderRadius(p.boxB,
borderRadius+"px");p.padM.style.background=p.sldM.style.background="#FFF";jsc.setStyle(p.padM,"opacity","0");jsc.setStyle(p.sldM,"opacity","0");p.pad.style.position="relative";p.pad.style.width=THIS.width+"px";p.pad.style.height=THIS.height+"px";p.padPal.draw(THIS.width,THIS.height,jsc.getPadYComponent(THIS));p.padB.style.position="absolute";p.padB.style.left=THIS.padding+"px";p.padB.style.top=THIS.padding+"px";p.padB.style.border=THIS.insetWidth+"px solid";p.padB.style.borderColor=THIS.insetColor;
p.padM._jscInstance=THIS;p.padM._jscControlName="pad";p.padM.style.position="absolute";p.padM.style.left="0";p.padM.style.top="0";p.padM.style.width=THIS.padding+2*THIS.insetWidth+THIS.width+padToSliderPadding/2+"px";p.padM.style.height=dims[1]+"px";p.padM.style.cursor=padCursor;p.cross.style.position="absolute";p.cross.style.left=p.cross.style.top="0";p.cross.style.width=p.cross.style.height=crossOuterSize+"px";p.crossBY.style.position=p.crossBX.style.position="absolute";p.crossBY.style.background=
p.crossBX.style.background=THIS.pointerBorderColor;p.crossBY.style.width=p.crossBX.style.height=2*THIS.pointerBorderWidth+THIS.pointerThickness+"px";p.crossBY.style.height=p.crossBX.style.width=crossOuterSize+"px";p.crossBY.style.left=p.crossBX.style.top=Math.floor(crossOuterSize/2)-Math.floor(THIS.pointerThickness/2)-THIS.pointerBorderWidth+"px";p.crossBY.style.top=p.crossBX.style.left="0";p.crossLY.style.position=p.crossLX.style.position="absolute";p.crossLY.style.background=p.crossLX.style.background=
THIS.pointerColor;p.crossLY.style.height=p.crossLX.style.width=crossOuterSize-2*THIS.pointerBorderWidth+"px";p.crossLY.style.width=p.crossLX.style.height=THIS.pointerThickness+"px";p.crossLY.style.left=p.crossLX.style.top=Math.floor(crossOuterSize/2)-Math.floor(THIS.pointerThickness/2)+"px";p.crossLY.style.top=p.crossLX.style.left=THIS.pointerBorderWidth+"px";p.sld.style.overflow="hidden";p.sld.style.width=THIS.sliderSize+"px";p.sld.style.height=THIS.height+"px";p.sldGrad.draw(THIS.sliderSize,THIS.height,
"#000","#000");p.sldB.style.display=displaySlider?"block":"none";p.sldB.style.position="absolute";p.sldB.style.right=THIS.padding+"px";p.sldB.style.top=THIS.padding+"px";p.sldB.style.border=THIS.insetWidth+"px solid";p.sldB.style.borderColor=THIS.insetColor;p.sldM._jscInstance=THIS;p.sldM._jscControlName="sld";p.sldM.style.display=displaySlider?"block":"none";p.sldM.style.position="absolute";p.sldM.style.right="0";p.sldM.style.top="0";p.sldM.style.width=THIS.sliderSize+padToSliderPadding/2+THIS.padding+
2*THIS.insetWidth+"px";p.sldM.style.height=dims[1]+"px";p.sldM.style.cursor="default";p.sldPtrIB.style.border=p.sldPtrOB.style.border=THIS.pointerBorderWidth+"px solid "+THIS.pointerBorderColor;p.sldPtrOB.style.position="absolute";p.sldPtrOB.style.left=-(2*THIS.pointerBorderWidth+THIS.pointerThickness)+"px";p.sldPtrOB.style.top="0";p.sldPtrMB.style.border=THIS.pointerThickness+"px solid "+THIS.pointerColor;p.sldPtrS.style.width=THIS.sliderSize+"px";p.sldPtrS.style.height=sliderPtrSpace+"px";function setBtnBorder(){var insetColors=
THIS.insetColor.split(/\s+/);var outsetColor=insetColors.length<2?insetColors[0]:insetColors[1]+" "+insetColors[0]+" "+insetColors[0]+" "+insetColors[1];p.btn.style.borderColor=outsetColor}p.btn.style.display=THIS.closable?"block":"none";p.btn.style.position="absolute";p.btn.style.left=THIS.padding+"px";p.btn.style.bottom=THIS.padding+"px";p.btn.style.padding="0 15px";p.btn.style.height=THIS.buttonHeight+"px";p.btn.style.border=THIS.insetWidth+"px solid";setBtnBorder();p.btn.style.color=THIS.buttonColor;
p.btn.style.font="12px sans-serif";p.btn.style.textAlign="center";try{p.btn.style.cursor="pointer"}catch(eOldIE){p.btn.style.cursor="hand"}p.btn.onmousedown=function(){THIS.hide()};p.btnT.style.lineHeight=THIS.buttonHeight+"px";p.btnT.innerHTML="";p.btnT.appendChild(document.createTextNode(THIS.closeText));redrawPad();redrawSld();if(jsc.picker.owner&&jsc.picker.owner!==THIS)jsc.unsetClass(jsc.picker.owner.targetElement,THIS.activeClass);jsc.picker.owner=THIS;if(jsc.isElementType(container,"body"))jsc.redrawPosition();
else jsc._drawPosition(THIS,0,0,"relative",false);if(p.wrap.parentNode!=container)container.appendChild(p.wrap);jsc.setClass(THIS.targetElement,THIS.activeClass)}function redrawPad(){switch(jsc.getPadYComponent(THIS)){case "s":var yComponent=1;break;case "v":var yComponent=2;break}var x=Math.round(THIS.hsv[0]/360*(THIS.width-1));var y=Math.round((1-THIS.hsv[yComponent]/100)*(THIS.height-1));var crossOuterSize=2*THIS.pointerBorderWidth+THIS.pointerThickness+2*THIS.crossSize;var ofs=-Math.floor(crossOuterSize/
2);jsc.picker.cross.style.left=x+ofs+"px";jsc.picker.cross.style.top=y+ofs+"px";switch(jsc.getSliderComponent(THIS)){case "s":var rgb1=HSV_RGB(THIS.hsv[0],100,THIS.hsv[2]);var rgb2=HSV_RGB(THIS.hsv[0],0,THIS.hsv[2]);var color1="rgb("+Math.round(rgb1[0])+","+Math.round(rgb1[1])+","+Math.round(rgb1[2])+")";var color2="rgb("+Math.round(rgb2[0])+","+Math.round(rgb2[1])+","+Math.round(rgb2[2])+")";jsc.picker.sldGrad.draw(THIS.sliderSize,THIS.height,color1,color2);break;case "v":var rgb=HSV_RGB(THIS.hsv[0],
THIS.hsv[1],100);var color1="rgb("+Math.round(rgb[0])+","+Math.round(rgb[1])+","+Math.round(rgb[2])+")";var color2="#000";jsc.picker.sldGrad.draw(THIS.sliderSize,THIS.height,color1,color2);break}}function redrawSld(){var sldComponent=jsc.getSliderComponent(THIS);if(sldComponent){switch(sldComponent){case "s":var yComponent=1;break;case "v":var yComponent=2;break}var y=Math.round((1-THIS.hsv[yComponent]/100)*(THIS.height-1));jsc.picker.sldPtrOB.style.top=y-(2*THIS.pointerBorderWidth+THIS.pointerThickness)-
Math.floor(sliderPtrSpace/2)+"px"}}function isPickerOwner(){return jsc.picker&&jsc.picker.owner===THIS}function blurValue(){THIS.importColor()}if(typeof targetElement==="string"){var id=targetElement;var elm=document.getElementById(id);if(elm)this.targetElement=elm;else jsc.warn("Could not find target element with ID '"+id+"'")}else if(targetElement)this.targetElement=targetElement;else jsc.warn("Invalid target element: '"+targetElement+"'");if(this.targetElement._jscLinkedInstance){jsc.warn("Cannot link jscolor twice to the same element. Skipping.");
return}this.targetElement._jscLinkedInstance=this;this.valueElement=jsc.fetchElement(this.valueElement);this.styleElement=jsc.fetchElement(this.styleElement);var THIS=this;var container=this.container?jsc.fetchElement(this.container):document.getElementsByTagName("body")[0];var sliderPtrSpace=3;if(jsc.isElementType(this.targetElement,"button"))if(this.targetElement.onclick){var origCallback=this.targetElement.onclick;this.targetElement.onclick=function(evt){origCallback.call(this,evt);return false}}else this.targetElement.onclick=
function(){return false};if(this.valueElement)if(jsc.isElementType(this.valueElement,"input")){var updateField=function(){THIS.fromString(THIS.valueElement.value,jsc.leaveValue);jsc.dispatchFineChange(THIS)};jsc.attachEvent(this.valueElement,"keyup",updateField);jsc.attachEvent(this.valueElement,"input",updateField);jsc.attachEvent(this.valueElement,"blur",blurValue);this.valueElement.setAttribute("autocomplete","off")}if(this.styleElement)this.styleElement._jscOrigStyle={backgroundImage:this.styleElement.style.backgroundImage,
backgroundColor:this.styleElement.style.backgroundColor,color:this.styleElement.style.color};if(this.value)this.fromString(this.value)||this.exportColor();else this.importColor()}};jsc.jscolor.lookupClass="jscolor";jsc.jscolor.installByClassName=function(className){var inputElms=document.getElementsByTagName("input");var buttonElms=document.getElementsByTagName("button");jsc.tryInstallOnElements(inputElms,className);jsc.tryInstallOnElements(buttonElms,className)};jsc.register();return jsc.jscolor}();
window.addEventListener("keydown",keydown);window.addEventListener("keyup",keyup);var Feed=false;var Dingus=false;var imlost=25;load();function load(){if(document.getElementById("overlays").style.display!="none");else setTimeout(load,100)}
function keydown(event){if(event.keyCode==87||event.keyCode==69){Feed=true;setTimeout(fukherriteindapussie,imlost)}if(event.keyCode==84||event.keyCode==90)for(var b=0;b<4;b++)setTimeout(ilikedick,b*50);if(event.keyCode==68){ilikedick();setTimeout(ilikedick,50)}if(event.keyCode==83){X=window.innerWidth/2;Y=window.innerHeight/2;$("canvas").trigger($.Event("mousemove",{clientX:X,clientY:Y}))}}function keyup(event){if(event.keyCode==81)Feed=false;if(event.keyCode==79)Dingus=false}
function fukherriteindapussie(){if(Feed){window.onkeydown({keyCode:87});window.onkeyup({keyCode:87});setTimeout(fukherriteindapussie,imlost)}}function ilikedick(){$("body").trigger($.Event("keydown",{keyCode:32}));$("body").trigger($.Event("keyup",{keyCode:32}))}; function closeIt() { return''; } window.onbeforeunload = closeIt;
